### ISSUE TITLE
Use native API to gather power information instead of system-profiler.

### ISSUE THREAD

**Issue by LanderN** [LanderN/WattMeter#8]
Relevant documentation:
https://developer.apple.com/documentation/iokit/1523867-iopsgetpowersourcedescription?language=objc
https://developer.apple.com/documentation/iokit/iopskeys.h/defines?language=objc

**Comment by TomasVanRoose** [comment]
An example i found here [here](https://stackoverflow.com/questions/43953132/extracting-value-from-iopscopypowersourcesinfo-swift?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa)

```Swift
import IOKit.ps

let psInfo = IOPSCopyPowerSourcesInfo().takeRetainedValue()
let psList = IOPSCopyPowerSourcesList(psInfo).takeRetainedValue() as [CFTypeRef]

for ps in psList {
    if let psDesc = IOPSGetPowerSourceDescription(psInfo, ps).takeUnretainedValue() as? [String: Any] {
        if let type = psDesc[kIOPSTypeKey] as? String,
            let isCharging = (psDesc[kIOPSIsChargingKey] as? Bool) {
            print(type, "is charging:", isCharging)
        }
    }
}
```

**Comment by LanderN** [comment]
I can get Battery Current and AC Watts using this method, but can't get Voltage. Looking for a workaround.
https://gist.github.com/khakionion/720a949b3beb5f6d1e4c might be interesting.
